# Generated by Django 5.2 on 2025-05-28 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(auto_created=True)),
                ('title', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=150)),
            ],
        ),
    ]
